---
title: "TidyTuesday 2020/28 - Coffee Ratings by James LeDoux & Coffee Quality Database"
author: "Cedric Scherer"
date: "7/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep}
## packages
library(tidyverse)
library(ggdist)
library(grid)
library(png)
library(ggtext)
library(ragg)
library(pdftools)

## ggplot theme
theme_set(theme_minimal(base_family = "Bebas Neue", base_size = 16))

theme_update(
  panel.grid = element_blank(),
  axis.title = element_blank(),
  axis.text = element_blank(),
  plot.background = element_rect(color = NA, fill = "#faf9f5")
)
```


```{r data}
df_coffee <- tidytuesdayR::tt_load(2020, week = 28)$coffee_ratings
```

```{r data-prep}
df_coffee_p <- 
  df_coffee %>% 
  filter(total_cup_points != 0) %>% 
  group_by(species, owner, country_of_origin, farm_name, mill, ico_number, harvest_year, grading_date) %>%
  summarise(total_cup_points = mean(total_cup_points)) %>% 
  group_by(country_of_origin) %>% 
  filter(n() > 25) %>% 
  mutate(
    med = median(total_cup_points),
    min = min(total_cup_points),
    n = n(),
    country_of_origin = case_when(
      country_of_origin == "Tanzania, United Republic Of" ~ "Tanzania",
      str_detect(country_of_origin, "United States") ~ "United States",
      TRUE ~ country_of_origin
    )
  ) %>% 
  ungroup() %>% 
  mutate(
    country = fct_reorder(country_of_origin, med),
    y = as.numeric(country) - .3
  )
```

```{r plot, fig.width=12.5, fig.height = 9}
img <- readPNG(here::here("img", "coffee.png"))
r <- rasterGrob(img, interpolate = TRUE)

df_coffee_sum <- 
  df_coffee_p %>% 
  group_by(country) %>% 
  slice(1)

df_labs <- 
  tibble(
    x = c(60.5, 88.2, 61.7, 86.2),
    y = c(6.2, 12.2, 1.2, 2.1),
     label = c("The coffee bean with the lowest\nrating has its origin in Guatemala.", 
               "The best coffee—in\nterms of both median and\nmaximum rating—is shipped\nto you from Ethiopia!", 
               "One bean from Nicaragua\ngot a bad rating, too.", 
               "With 218 tested beans,\nMexico is the country with\nthe most reviews.")
  )

ggplot(df_coffee_p, aes(
  x = total_cup_points,
  y = y
)) +
  annotation_custom(r, xmin = 59, xmax = 65, ymin = -1, ymax = 4.5) +
  ## labels countries
  geom_text(
    data = df_coffee_sum,
    aes(
      x = min,
      y = y,
      label = country,
      size = n
    ),
    family = "Bebas Neue",
    color = "grey88",
    fontface = "bold",
    vjust = 0,
    hjust = -0.01
  ) +
  ## stripe
  stat_interval(
    aes(y = y - .05),
    orientation = "horizontal",
    .width = c(.25, .5, .95, 1),
    stroke = 0,
    size = 1.4
  ) +
  ## indicator median
  geom_point(
    data = df_coffee_sum,
    aes(x = med, y = y - .18),
    shape = 17,
    color = "grey20",
    size = 2
  ) +
  geom_text(
    data = df_coffee_sum,
    aes(
      x = med + .16,
      y = y - .11,
      label = glue::glue("{round(med, 1)} points")
    ),
    family = "Bebas Neue",
    color = "grey20",
    size = 2.5,
    vjust = 1,
    hjust = 0
  ) +
  ## indicator minimum 
  geom_point(
    data = df_coffee_sum,
    aes(x = min + .01, y = y - .19),
    shape = 2,
    color = "firebrick",
    size = 1.9
  ) +
  geom_text(
    data = df_coffee_sum,
    aes(
      x = min + .16,
      y = y - .11,
      label = glue::glue("{round(min, 1)} points")
    ),
    family = "Bebas Neue",
    color = "grey20",
    size = 2.5,
    vjust = 1,
    hjust = 0
  ) +
  ## dots
  stat_dots(
    quantiles = NA,
    orientation = "horizontal",
    normalize = "none",
    scale = .87,
    color = "#6f4e37",
    fill = "#6f4e37"
  ) +
  ## labels axis
  geom_text(
    data = tibble(
      x = seq(60, 90, by = 10),
      y = 8.385,
      label = glue::glue("{seq(60, 90, by = 10)} points")
    ),
    aes(
      x = x,
      y = y,
      label = label
    ),
    inherit.aes = F,
    family = "Bebas Neue",
    color = "grey65",
    size = 3.5
  )+
  geom_point(
    data = tibble(
      x = rep(seq(60, 90, by = 10), 2),
      y = rep(c(8.55, 8.22), each = 4),
    ),
    aes(
      x = x,
      y = y
    ),
    inherit.aes = F,
    color = "grey65",
    shape = "|",
    size = 1
  ) +
  ## annotations
  geom_text(
    data = df_labs,
    aes(x, y, label = label),
    inherit.aes = F,
    family = "Arapey",
    color = "#99754d",
    size = 2.8,
    lineheight = .87
  )  +
  scale_x_continuous(
    breaks = seq(60, 90, by = 10),
    labels = function(x) paste0(x, " points")
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_color_manual(
    values = c("grey85", "#ccbe9b", "#e8984e", "#94350b"),
    guide = F
  ) +
  scale_size(
    range = c( 8.75, 15.5),
    guide = F
  )
  

```

```{r save-convert}
ggsave(here::here("plots", "2020_28", "2020_28_CoffeeRatings.pdf"), 
      width = 12.5, height = 9, device = cairo_pdf)
## convert to png
pdf_convert(pdf = here::here("plots", "2020_28", "2020_28_CoffeeRatings.pdf"),
              format = "png", dpi = 400)
```